### ISSUE TITLE
Empty show protocols tables, error "couldn't parse" in lg.log

### ISSUE THREAD

**Issue by cherdt** [sileht/bird-lg#36]
I just installed and configured bird 2.0.2 and bird-lg, so this may be an issue with my config. I am running bird, lgproxy.py, and lg.py on the same host. I'm using the current master branch (1f0efca) for bird-lg.

I can successfully query the proxy via curl:

```
$ curl http://localhost:5001/bird?q=show%20protocols
Name       Proto      Table      State  Since         Info
peer1      BGP        ---        up     13:04:05.471  Established
``` 
However, on the _show protocols_ page of the looking glass (e.g. http://lg.example.com:5000/summary/lg/ipv4) the table contains only the header and one empty row.

The log in `/var/log/lg.log` contains a new entry every time I try to reload the show protocols page in the looking glass:

```
couldn't parse: peer1      BGP        ---        up     13:04:05.471  Established
```

It looks like the issue is that the table column, '---', doesn't match the regular expression.

I do see that vpn4tab is populated:

```
$ sudo /usr/local/sbin/birdc show route count
BIRD v2.0.2 ready.
0 of 0 routes for 0 networks in table master4
0 of 0 routes for 0 networks in table master6
9581 of 9581 routes for 9581 networks in table vpntab4
Total: 9581 of 9581 routes for 9581 networks in 3 tables
```

I'm guessing that the table is showing '---' because there are other tables (master4 and master6) present? I'm not sure if bird-lg should be able to handle this, or if my bird configuration needs to somehow exclude the master4 and master6 tables.

My `bird.conf` file is below:

```
log syslog { debug, trace, info, remote, warning, error, auth, fatal, bug };
log stderr all;

router id 127.0.0.1;

vpn4 table vpntab4;
vpn6 table vpntab6;

protocol bgp peer1 {
        local as 65321;
        neighbor 192.168.1.1 as 65321;
        hold time 180;
        vpn4 mpls {
                import all;
                export all;
        };
        vpn6 mpls {
                import all;
                export all;
        };
}
```

**Comment by zhaofengli** [comment]
Looks like bird-lg doesn't play well with output from Bird 2.x. I messed around for a few minutes and came up with this replacement regex:
```
SUMMARY_RE_MATCH = r"(?P<name>[\w_]+)\s+(?P<proto>\w+)\s+(?P<table>[\w\-]+)\s+(?P<state>\w+)\s+(?P<since>((|\d\d\d\d-\d\d-\d\d)|(\d\d:)\d\d:\d\d|\d\d:\d\d:\d\d.\d\d\d|\w\w\w\d\d))($|\s+(?P<info>.*))"
```
