### ISSUE TITLE
BIND_ADDR and BIND_PORT ignored when run by "flask run"

### ISSUE THREAD

**Issue by athompson-merlin** [sileht/bird-lg#62]
No matter what starting lg.py or lgproxy.py via `flask run` always launches on 127.0.0.1:5000, overriding even hardcoded values in the source code.  This violates POLA rather significantly.
Please document how to run the app under flask's development server, for those of us who aren't flask programmers.

**Comment by athompson-merlin** [comment]
(and yes, I eventually found the --host and --port options)

**Comment by zorun** [comment]
Hi,

I'm not sure I understand the problem, can you be more specific?

The code can simply be run with python:

```shell
python2 lgproxy.py
```
